---
- hosts: all
  become: true
  become_method: sudo
  vars:
    httpd:
      release: 54.el6.centos
  tasks:
    - name: Remove HTTPD
      yum:
        name: httpd
        state: absent
    - name: Remove HTTPD Tools
      yum:
        name: httpd-tools
        state: absent
    - name: Remove mod SSL
      yum:
        name: mod_ssl
        state: absent
    - name: Install HTTPD
      yum:
        name: httpd-2.2.15-{{ httpd.release }}
        state: present
    - name: Install HTTPD Tools
      yum:
        name: httpd-tools-2.2.15-{{ httpd.release }}
        state: present
    - name: Install mod SSL
      yum:
        name: mod_ssl-2.2.15-{{ httpd.release }}
        state: present
      notify:
        - restart apache
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
